apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-dep
  namespace: next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next
          image: xanderflinn/next-yt:bd3268f474a011fa693264ac67e7622f018c12db
          ports:
            - containerPort: 3000
