apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: next-secret
  namespace: next
spec:
  encryptedData:
    .env: AgA6fg7uKoh3t9Fvqggg15DE/MStvxDWjKjJxgjI1VLXWMlAIgxnhuQGJPxMK/NzAXSEwXp6+iadMTwAjoKkmbxeu9DvMJu2z/Njl4mTXbTA7dYliTE5rTPZ6Smlmm+tNC0g0TYTwWdbV8vfohLF7bT6knNG4ZQBAYBVoYmvImzCCu9WpS0LNz28NCR3LPfo2acRMFZROnusoxQksP3jcO53Lf2QrnOWqvOiqATlUEnPDQNMHLnbGU1tslvX8taXWF+nl8g6lO54hzpO8mptPWOfqQkJdPo3xXOPNkY/BlzT33Nt2/hIWV1KDL0AinS29nvF0pDqAqqtGf40f44T8Re2xgjbczOofHCDgurZ+Yka0rhOFfJ004VTJhAHgXa76EUzo3gqv3+Gi+ZEgrb+iE95yVEI6XrKb+Vo2uFwuybpiCwfLtSO18KJli+nWISu6WaCe5vM7x19bo46DplIsJkluWrrh6+9MaFgF9IwiG0rMdmX+5WRs28rHyLxsA8PeQ9P1PatMEaOb2EVtb5vUhS4FF9e+879Mw7c7qJ1SafdLbeA+Jjwu5oLtZne3uAHeyMOJ57XSEZQ3KP41CaCNWOw4S363o4Kezze/VfUhgjwiYfpT5N3Zf5l3c6ZUzFDpLFAhzQOTQxYLTHOAWKtIsvE1qdgV34LnuA2jMyYJxabjwC3rHnyq81sG0FogC5N+pi7BnY7DYyIn4AhcJRp2QzoQEh9FiP4JnXj+uFBYcpt+iQiN2L+rlpogUnP6YBNRXknzWqVBLU9VZ6nkqFxTkrg7J8d07yltCxNWcrouHpU05JXUi3o
  template:
    metadata:
      name: next-secret
      namespace: next
