replicaCount: 3
image:
  repository: xanderflinn/next-yt
  tag: "d0b6112b6c9f6e1a591c0264b6c50e53c0ce2f3e"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 50
