replicaCount: 2
image:
  repository: polinux/stress
  tag: "latest"
  pullPolicy: IfNotPresent

stress:
  cpu: 2

service:
  enabled: false
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: nginx

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 50
