replicaCount: 1
image:
  repository: xanderflinn/cpu-app
  tag: "2"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: nginx

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 50
