apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--cpu"
            - "{{ .Values.stress.cpu }}"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
